### PR TITLE
adding JPD16 advanced workshop

### PR DESCRIPTION
**Pull request by ernesmb**
please @jsanz review

### CODE REVIEW

**Comment by ernesmb** [comment]
I still need to update the first `Plnkr` with a different `viz.json`, coming from the result of ramiro's part

**Comment by jsanz** [comment]
The FOSS4G Argentina SQL section had a viz with examples of the queries, why not using it here?

Also you don't specify a dataset to use on the different examples, are you not going to ask them to do the exercises so this is more like a long demo?

**Comment by ernesmb** [comment]
Do you mean the cdbfiddle example? I must have missed it, should be a good idea to save some time. Going to include it for sure. 

We are planning to use an ad-hoc cartodb account for the two workshops, with the datasets already imported, but attendants may need to import them from Data Library on their accounts. (Having an onpremise instance ready for trainings that we can turn on and off would be a good idea, but that's another subject)

The workshops are only 1,5h so I don't think there is time for a really interactive session. I was thinking more of a long, semi-interactive demo. The queries and code are there for the participants to explore and use them, but I need to keep a pace if I want to cover the minimum. 

Thanks for the review, going to update the PR 👍

**Comment by jsanz** [comment]
Agree, better a long demo and let only the smartest to follow you on their
computers.

Anyway, adding the original datasets (you can take them from BsAs workshop)
is good idea for those who want to try at home :-)

On Thu, May 5, 2016 at 10:54 AM, Ernesto Martínez Becerra <
notifications@github.com> wrote:

> Do you mean the cdbfiddle example? I must have missed it, should be a good
> idea to save some time. Going to include it for sure.
> 
> We are planning to use an ad-hoc cartodb account for the two workshops,
> with the datasets already imported, but attendants may need to import them
> from Data Library on their accounts. (Having an onpremise instance ready
> for trainings that we can turn on and off would be a good idea, but that's
> another subject)
> 
> The workshops are only 1,5h so I don't think there is time for a really
> interactive session. I was thinking more of a long, semi-interactive demo.
> The queries and code are there for the participants to explore and use
> them, but I need to keep a pace if I want to cover the minimum.
> 
> Thanks for the review, going to update the PR 👍
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/CartoDB/training/pull/8#issuecomment-217106021

## 

Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data

**Comment by ernesmb** [comment]
what do you think? any suggestion? @jsanz @ramiroaznar @nerik

**Comment by nerik** [comment]
Looks very good 👍 

A few comments:
- the point of the buffer example (4) is not clear until you zoom in, I'd make the radius larger so that the polygons are not mistaken for points
- the 100km example might be a bit clearer if you'd ST_MakeLine between each 2 cities (I'm thinking of smth similar to https://f.hypotheses.org/wp-content/blogs.dir/1381/files/2016/04/Nuitdeboutabstrait-720x340.png)
- rect and hex grids examples are really cool, make sure to introduce them with a practical use case 
- I would avoid using `a` and `b` for table names (rather `cities` and `countries`, idk)

**Comment by jsanz** [comment]
Agree on Erik's comments, looks great!

On Thu, May 5, 2016 at 3:55 PM, Erik Escoffier notifications@github.com
wrote:

> Looks very good 👍
> 
> A few comments:
> - the point of the buffer example (4) is not clear until you zoom in,
>   I'd make the radius larger so that the polygons are not mistaken for points
> - the 100km example might be a bit clearer if you'd ST_MakeLine
>   between each 2 cities (I'm thinking of smth similar to
>   https://f.hypotheses.org/wp-content/blogs.dir/1381/files/2016/04/Nuitdeboutabstrait-720x340.png
>   )
> - rect and hex grids examples are really cool, make sure to introduce
>   them with a practical use case
> - I would avoid using a and b for table names (rather cities and
>   countries, idk)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/CartoDB/training/pull/8#issuecomment-217160846

## 

Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data

**Comment by ernesmb** [comment]
I updated the PR with the suggested changes, thanks for the reviewing!

I am still going to keep the `a`, `b` aliases as they keep a cleaner 'look'

**Comment by jsanz** [comment]
Vamos!

On Thu, May 5, 2016 at 4:48 PM, Ernesto Martínez Becerra <
notifications@github.com> wrote:

> I updated the PR with the suggested changes, thanks for the reviewing!
> 
> I am still going to keep the a, b aliases as they keep a cleaner 'look'
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/CartoDB/training/pull/8#issuecomment-217174007

## 

Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data

**Pull request merged**
