### PR TITLE
BU Workshop commit

### PR DESCRIPTION
**Pull request by namessanti**
@auremoser @ohasselblad  can you check this out and merge please?

### CODE REVIEW

**Comment by namessanti** [comment]
screen shot 2015-06-25 at 4 19 58 pm
screen shot 2015-06-25 at 4 20 21 pm
screen shot 2015-06-25 at 4 20 35 pm

**Comment by auremoser** [comment]
Beautiful!

**Comment by piensaenpixel** [comment]
Uhmm what is this? Could we help you? :)

**Comment by andy-esch** [comment]
We'd love help!!

It's our repository for workshops that we've given around the world.

**Comment by auremoser** [comment]
workshops and talks! i think we soft launched a while ago but thought that it was mostly a "community" project and not at the level of Academy or other resources that we offer (perhaps now that the style guide is up we could match brand a bit better!). 

Like @ohasselblad said, we love help :)

**Comment by piensaenpixel** [comment]
Sure, tomorrow my leapfrog ;)

**Comment by andy-esch** [comment]
:+1: x 1000

**Comment by namessanti** [comment]
Woo woo!

**Pull request merged**
