### PR TITLE
fixing the highlihter 

### PR DESCRIPTION
**Pull request by jsanz**
to use kramdown and rouge instead of redcarpet/pygments

This should be rendered without major problems by GitHub pages now so it's ready to accept new contributions :smile:

### CODE REVIEW

**Comment by jsanz** [comment]
I've assigned @ohasselblad just looking at last year commits but maybe any other (@namessanti ?) can code review the changes.

**Comment by andy-esch** [comment]
:+1:, assigning to me ok, will get this done today

**Comment by jsanz** [comment]
Hey @ohasselblad can you take a look on this? Next Tuesday I have a workshop and I'm working on [a version of this repo on my account](https://github.com/jsanz/cartodb-workshop) only with my stuff but I'd prefer to be able to give a final URL for the materials and so on.

**Comment by andy-esch** [comment]
LGTM! Sorry for the delay.

`jekyll` is behaving strangely.. I had to run `bundle exec jekyll serve` to preview it, but all looks ok :+1:

**Comment by jsanz** [comment]
No prob :smile: Yeah I have to run always that command to be sure to use the versions stated on the `Gemfile.lock` file.

**Pull request merged**
